Creating array:

In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5,6]) # 1d array

In [3]:
b = np.arange(1,13) 
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
c = np.random.randint(1,100,24).reshape(6,4)
c

array([[70,  9, 15,  3],
       [91, 72, 25, 45],
       [79, 30, 99, 34],
       [16, 60, 26, 47],
       [99, 49, 77,  3],
       [21, 42, 28, 86]], dtype=int32)

In [5]:
d = np.linspace(1,100,6)
d

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [6]:
e = np.arange(1,25).reshape(3,4,2)
e

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [7]:
f = np.ones(12).reshape(3,4)
print(f"Array with all element 1 :\n{f}")

Array with all element 1 :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
j = np.zeros(24).reshape(4,6)
print(f"Array with all Zeros: {j}")

Array with all Zeros: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
i = np.identity(6)
i.size
i.shape
i.itemsize
i.dtype
i.nbytes

288

Attributes:

In [10]:
print("Dimension of array: ",e.ndim)
print("shape of array: ", e.shape)
print("Size of whole arry: ", e.size)
print("Total number of bits used by the array: ",e.nbytes)
print("Data types of the array: ", e.dtype)
print("item wise elements size", e.itemsize)



Dimension of array:  3
shape of array:  (3, 4, 2)
Size of whole arry:  24
Total number of bits used by the array:  192
Data types of the array:  int64
item wise elements size 8


Chinging Datatype:

In [11]:
print(i.nbytes)
i = np.astype(i,np.int8)
print(i.nbytes)

288
36


Array Operations:

In [12]:
k = np.arange(12).reshape(3,4)
l = np.arange(12,24).reshape(3,4)

In [13]:
k + l
k % l
k - l
k / l
k.nbytes == l.nbytes
k.itemsize == l.itemsize
k.dtype == l.dtype


True

In [14]:
k * 2 * l

array([[  0,  26,  56,  90],
       [128, 170, 216, 266],
       [320, 378, 440, 506]])

In [15]:
3 * l

array([[36, 39, 42, 45],
       [48, 51, 54, 57],
       [60, 63, 66, 69]])

In [16]:
3 * k

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [17]:
a2 = np.random.random((3,3))
a2 = np.round(a2 * 100)
a2

array([[73., 95., 60.],
       [84., 77., 50.],
       [11., 18., 12.]])

In [18]:
a2_min = np.min(a2,axis=0)
a2_min
a2_max = np.max(a2)
a2_max


np.float64(95.0)

In [19]:
np.round(np.std(a2))

np.float64(31.0)

In [20]:
np.round(np.mean(a2,axis=1))


array([76., 70., 14.])

In [21]:
a2

array([[73., 95., 60.],
       [84., 77., 50.],
       [11., 18., 12.]])

In [22]:
print(a2)
print(a)

[[73. 95. 60.]
 [84. 77. 50.]
 [11. 18. 12.]]
[1 2 3 4 5 6]


In [23]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
b = np.arange(12,24).reshape(3,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
dot_product = np.dot(a,b)
dot_product

array([[ 56,  59,  62,  65],
       [200, 212, 224, 236],
       [344, 365, 386, 407],
       [488, 518, 548, 578]])

In [26]:
a1 = np.random.random((3,3))
a1

array([[0.31623917, 0.83017431, 0.44527198],
       [0.0146951 , 0.39683707, 0.28512066],
       [0.83400241, 0.54483362, 0.23442646]])

In [27]:
np.exp(a1)

array([[1.37195835, 2.29371852, 1.56091467],
       [1.01480361, 1.48711362, 1.32992248],
       [2.30251594, 1.72432147, 1.26418351]])

In [28]:
np.log(a1)

array([[-1.15125647, -0.18611959, -0.80907   ],
       [-4.22024088, -0.92422948, -1.25484283],
       [-0.18151899, -0.60727481, -1.45061332]])

In [29]:
np.round(np.random.random((2,3)) * 100)

array([[19., 24., 21.],
       [ 0., 85., 42.]])

In [30]:
a1  = np.arange(1,10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [31]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1[1:3:]

array([2, 3])

In [33]:
a1[-1]
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
a2[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [35]:
a2[2:,0:1]

array([[8]])

In [36]:
a2[0:2,2:]

array([[2, 3],
       [6, 7]])

In [37]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a2[::2,2::]

array([[ 2,  3],
       [10, 11]])

In [39]:
a2[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a2[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [42]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a3[0::,1:]

array([[[2, 3]],

       [[6, 7]]])

In [44]:
a3[1:,1,0]

array([6])

In [45]:
a3[1:,1,0]

array([6])

In [46]:
a3[0:,0,1]

array([1, 5])

In [47]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
a3[1,0,1]
import sys
sys.getsizeof(a3)

144

In [49]:
a3 = np.astype(a3, np.int16)
sys.getsizeof(a3)

160

In [50]:
a = np.arange(1,25).reshape(4,2,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [51]:
a[0::,0::]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [52]:
matrix = np.array([[1, 2], 
                   [3, 4], 
                   [5, 6]])
rows = [0,2]
columns = [0,1]
matrix[rows,columns]

array([1, 6])

In [53]:
import numpy as np

# A 3D array: (Layers, Rows, Columns)
# Shape: (3, 4, 4)
data_3d = np.arange(48).reshape(3, 4, 4)

# print("The 3D Array:")
# print(data_3d)

In [54]:
# layer = [0,1,2]
# rows = [0,1,2]
# column = [1,1,2]

# data_3d[layer,rows,column]
# data_3d

In [55]:
# layers = [0, 1, 2]
# rows   = [1, 2, 0]
# cols   = [2, 3, 0]
# data_3d[layer,rows,cols]

layers = [0,1]
rows = [1,3]
cols = [3,3]
data_3d[layers,rows,cols]
data_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [56]:
layers = [2,1,0]
rows = [2,3,2]
cols = [2,3,2]
print(data_3d[layers,rows,cols])
data_3d[[2,1,0],[2,3,2],[2,3,2]]

[42 31 10]


array([42, 31, 10])

In [57]:
# for i in np.nditer(data_3d):
#     print(i)

reshape = np.transpose(data_3d)
reshapes = np.transpose(np.transpose(data_3d))
print(reshape)
print(reshapes)


[[[ 0 16 32]
  [ 4 20 36]
  [ 8 24 40]
  [12 28 44]]

 [[ 1 17 33]
  [ 5 21 37]
  [ 9 25 41]
  [13 29 45]]

 [[ 2 18 34]
  [ 6 22 38]
  [10 26 42]
  [14 30 46]]

 [[ 3 19 35]
  [ 7 23 39]
  [11 27 43]
  [15 31 47]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


In [58]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [61]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [64]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.hsplit(a4,2)
print(a5) 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [66]:
np.hsplit(a5,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [67]:
s = "python"
print("_".join(s[::-1]))
new = "_".join(s)
print(new[::-1])

n_o_h_t_y_p
n_o_h_t_y_p


In [68]:
a = np.random.randint(1,100,25)
a

array([66, 28, 60, 69, 44, 28, 73, 36, 18, 71, 76, 78, 57, 40, 73, 99, 95,
       73, 63, 92, 79, 66, 52, 84, 54], dtype=int32)

In [69]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[95, 27, 57, 11],
       [84, 87, 34, 11],
       [77, 29, 42, 80],
       [91, 84, 76, 86],
       [71, 12, 66, 12],
       [93, 18, 25, 57]], dtype=int32)

In [70]:
new_a = sorted(a)
new_a = np.array(new_a)
new_a

array([18, 28, 28, 36, 40, 44, 52, 54, 57, 60, 63, 66, 66, 69, 71, 73, 73,
       73, 76, 78, 79, 84, 92, 95, 99], dtype=int32)

In [71]:
np.sort(a)
a.ndim

1

In [72]:
b

array([[95, 27, 57, 11],
       [84, 87, 34, 11],
       [77, 29, 42, 80],
       [91, 84, 76, 86],
       [71, 12, 66, 12],
       [93, 18, 25, 57]], dtype=int32)

In [73]:
"By default it will sort the array both row and column wise..."
print(np.sort(b))
print(b)

[[11 27 57 95]
 [11 34 84 87]
 [29 42 77 80]
 [76 84 86 91]
 [12 12 66 71]
 [18 25 57 93]]
[[95 27 57 11]
 [84 87 34 11]
 [77 29 42 80]
 [91 84 76 86]
 [71 12 66 12]
 [93 18 25 57]]


In [74]:
np.sort(b,axis=0)

array([[71, 12, 25, 11],
       [77, 18, 34, 11],
       [84, 27, 42, 12],
       [91, 29, 57, 57],
       [93, 84, 66, 80],
       [95, 87, 76, 86]], dtype=int32)

In [75]:
a

array([66, 28, 60, 69, 44, 28, 73, 36, 18, 71, 76, 78, 57, 40, 73, 99, 95,
       73, 63, 92, 79, 66, 52, 84, 54], dtype=int32)

In [76]:
np.append(a,200)

array([ 66,  28,  60,  69,  44,  28,  73,  36,  18,  71,  76,  78,  57,
        40,  73,  99,  95,  73,  63,  92,  79,  66,  52,  84,  54, 200])

In [77]:
new_array = [1,2,3]
np.append(a,new_array)
b

array([[95, 27, 57, 11],
       [84, 87, 34, 11],
       [77, 29, 42, 80],
       [91, 84, 76, 86],
       [71, 12, 66, 12],
       [93, 18, 25, 57]], dtype=int32)

In [78]:
new_array = np.array([100,200,300,400,500,600]).reshape(6,1)
np.append(b,new_array,axis=1)

array([[ 95,  27,  57,  11, 100],
       [ 84,  87,  34,  11, 200],
       [ 77,  29,  42,  80, 300],
       [ 91,  84,  76,  86, 400],
       [ 71,  12,  66,  12, 500],
       [ 93,  18,  25,  57, 600]])

In [79]:
# new_array = np.array([100,200,300,400]).reshape(1,4)
# np.append(b,new_array,axis=0)

In [80]:
"Other and best approaches:"
print(np.column_stack((b,new_array)).shape)
print(np.column_stack((b,new_array)))

(6, 5)
[[ 95  27  57  11 100]
 [ 84  87  34  11 200]
 [ 77  29  42  80 300]
 [ 91  84  76  86 400]
 [ 71  12  66  12 500]
 [ 93  18  25  57 600]]


In [81]:
new_array = [100,200,300,400]
np.row_stack((b,new_array)) 
"DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly (for the above)"
np.vstack((b,new_array))

C:\Users\ztech.pk\AppData\Local\Temp\ipykernel_8424\1338226842.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((b,new_array))


array([[ 95,  27,  57,  11],
       [ 84,  87,  34,  11],
       [ 77,  29,  42,  80],
       [ 91,  84,  76,  86],
       [ 71,  12,  66,  12],
       [ 93,  18,  25,  57],
       [100, 200, 300, 400]])

In [82]:
np.append(b,np.random.randint(100,700,6).reshape(6,1),axis=1)

array([[ 95,  27,  57,  11, 417],
       [ 84,  87,  34,  11, 384],
       [ 77,  29,  42,  80, 232],
       [ 91,  84,  76,  86, 658],
       [ 71,  12,  66,  12, 481],
       [ 93,  18,  25,  57, 598]], dtype=int32)

In [83]:
np.append(b,np.random.randint(100,500,4).reshape(1,4),axis=0)

array([[ 95,  27,  57,  11],
       [ 84,  87,  34,  11],
       [ 77,  29,  42,  80],
       [ 91,  84,  76,  86],
       [ 71,  12,  66,  12],
       [ 93,  18,  25,  57],
       [342, 418, 479, 167]], dtype=int32)

In [84]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [85]:
print(c + d)
print()
print(np.concatenate((c,d),axis=0))
print()
print(np.concatenate((c,d),axis=1))

[[ 6  8 10]
 [12 14 16]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [86]:
f = np.array([1,1,2,2,3,3,4,4,5,5])
np.unique(f)


array([1, 2, 3, 4, 5])

In [87]:
# print(b)

# np.where(b > 50) 
"three arguments: first-condition, second value on which element will be replaced and third if condition false then replace with that value:"
np.where(b>50,50,40)
b

array([[95, 27, 57, 11],
       [84, 87, 34, 11],
       [77, 29, 42, 80],
       [91, 84, 76, 86],
       [71, 12, 66, 12],
       [93, 18, 25, 57]], dtype=int32)

In [88]:
np.argmax(b)

np.int64(0)

In [89]:
"along the columns"
np.argmax(b,axis=0)

array([0, 1, 3, 3])

In [90]:
"along the rows"
np.argmax(b,axis=1)

array([0, 1, 3, 0, 0, 0])

In [91]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [92]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15])

In [93]:
b

array([[95, 27, 57, 11],
       [84, 87, 34, 11],
       [77, 29, 42, 80],
       [91, 84, 76, 86],
       [71, 12, 66, 12],
       [93, 18, 25, 57]], dtype=int32)

In [94]:
np.cumsum(b)

array([  95,  122,  179,  190,  274,  361,  395,  406,  483,  512,  554,
        634,  725,  809,  885,  971, 1042, 1054, 1120, 1132, 1225, 1243,
       1268, 1325])

In [95]:
"along columns"
np.cumsum(b,axis=0)

array([[ 95,  27,  57,  11],
       [179, 114,  91,  22],
       [256, 143, 133, 102],
       [347, 227, 209, 188],
       [418, 239, 275, 200],
       [511, 257, 300, 257]])

In [96]:
"Along rows:"
np.cumsum(b,axis=1)

array([[ 95, 122, 179, 190],
       [ 84, 171, 205, 216],
       [ 77, 106, 148, 228],
       [ 91, 175, 251, 337],
       [ 71,  83, 149, 161],
       [ 93, 111, 136, 193]])

In [97]:
np.cumprod(b,axis=0)

array([[          95,           27,           57,           11],
       [        7980,         2349,         1938,          121],
       [      614460,        68121,        81396,         9680],
       [    55915860,      5722164,      6186096,       832480],
       [  3970026060,     68665968,    408282336,      9989760],
       [369212423580,   1235987424,  10207058400,    569416320]])

In [98]:
np.cumprod(b,axis=1)

array([[      95,     2565,   146205,  1608255],
       [      84,     7308,   248472,  2733192],
       [      77,     2233,    93786,  7502880],
       [      91,     7644,   580944, 49961184],
       [      71,      852,    56232,   674784],
       [      93,     1674,    41850,  2385450]])