Creating array:

In [2]:
import numpy as np


In [3]:
a = np.array([1,2,3,4,5,6]) # 1d array

In [4]:
b = np.arange(1,13) 
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
c = np.random.randint(1,100,24).reshape(6,4)
c

array([[54, 24, 39, 11],
       [91, 31, 14, 69],
       [12, 75, 62, 42],
       [13, 61, 19, 85],
       [90, 65, 34, 95],
       [ 7, 94, 67, 80]], dtype=int32)

In [6]:
d = np.linspace(1,100,6)
d

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [7]:
e = np.arange(1,25).reshape(3,4,2)
e

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [8]:
f = np.ones(12).reshape(3,4)
print(f"Array with all element 1 :\n{f}")

Array with all element 1 :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
j = np.zeros(24).reshape(4,6)
print(f"Array with all Zeros: {j}")

Array with all Zeros: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
i = np.identity(6)
i.size
i.shape
i.itemsize
i.dtype
i.nbytes

288

Attributes:

In [24]:
print("Dimension of array: ",e.ndim)
print("shape of array: ", e.shape)
print("Size of whole arry: ", e.size)
print("Total number of bits used by the array: ",e.nbytes)
print("Data types of the array: ", e.dtype)
print("item wise elements size", e.itemsize)



Dimension of array:  3
shape of array:  (3, 4, 2)
Size of whole arry:  24
Total number of bits used by the array:  192
Data types of the array:  int64
item wise elements size 8


Chinging Datatype:

In [27]:
print(i.nbytes)
i = np.astype(i,np.int8)
print(i.nbytes)

288
36


Array Operations:

In [29]:
k = np.arange(12).reshape(3,4)
l = np.arange(12,24).reshape(3,4)

In [ ]:
k + l
k % l
k - l
k / l
k.nbytes == l.nbytes
k.itemsize == l.itemsize
k.dtype == l.dtype


True