Creating array:

In [175]:
import numpy as np


In [176]:
a = np.array([1,2,3,4,5,6]) # 1d array

In [177]:
b = np.arange(1,13) 
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [178]:
c = np.random.randint(1,100,24).reshape(6,4)
c

array([[96, 83, 91, 26],
       [ 2,  9, 56, 76],
       [70, 37, 28, 37],
       [94, 56, 47,  3],
       [26, 13, 79, 81],
       [49, 42,  5, 49]], dtype=int32)

In [179]:
d = np.linspace(1,100,6)
d

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [180]:
e = np.arange(1,25).reshape(3,4,2)
e

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [181]:
f = np.ones(12).reshape(3,4)
print(f"Array with all element 1 :\n{f}")

Array with all element 1 :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [182]:
j = np.zeros(24).reshape(4,6)
print(f"Array with all Zeros: {j}")

Array with all Zeros: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [183]:
i = np.identity(6)
i.size
i.shape
i.itemsize
i.dtype
i.nbytes

288

Attributes:

In [184]:
print("Dimension of array: ",e.ndim)
print("shape of array: ", e.shape)
print("Size of whole arry: ", e.size)
print("Total number of bits used by the array: ",e.nbytes)
print("Data types of the array: ", e.dtype)
print("item wise elements size", e.itemsize)



Dimension of array:  3
shape of array:  (3, 4, 2)
Size of whole arry:  24
Total number of bits used by the array:  192
Data types of the array:  int64
item wise elements size 8


Chinging Datatype:

In [185]:
print(i.nbytes)
i = np.astype(i,np.int8)
print(i.nbytes)

288
36


Array Operations:

In [186]:
k = np.arange(12).reshape(3,4)
l = np.arange(12,24).reshape(3,4)

In [187]:
k + l
k % l
k - l
k / l
k.nbytes == l.nbytes
k.itemsize == l.itemsize
k.dtype == l.dtype


True

In [188]:
k * 2 * l

array([[  0,  26,  56,  90],
       [128, 170, 216, 266],
       [320, 378, 440, 506]])

In [189]:
3 * l

array([[36, 39, 42, 45],
       [48, 51, 54, 57],
       [60, 63, 66, 69]])

In [190]:
3 * k

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [191]:
a2 = np.random.random((3,3))
a2 = np.round(a2 * 100)
a2

array([[66., 73.,  3.],
       [80.,  3., 24.],
       [18., 86.,  9.]])

In [192]:
a2_min = np.min(a2,axis=0)
a2_min
a2_max = np.max(a2)
a2_max


np.float64(86.0)

In [193]:
np.round(np.std(a2))

np.float64(33.0)

In [194]:
np.round(np.mean(a2,axis=1))


array([47., 36., 38.])

In [195]:
a2

array([[66., 73.,  3.],
       [80.,  3., 24.],
       [18., 86.,  9.]])

In [196]:
print(a2)
print(a)

[[66. 73.  3.]
 [80.  3. 24.]
 [18. 86.  9.]]
[1 2 3 4 5 6]


In [197]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [198]:
b = np.arange(12,24).reshape(3,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [199]:
dot_product = np.dot(a,b)
dot_product

array([[ 56,  59,  62,  65],
       [200, 212, 224, 236],
       [344, 365, 386, 407],
       [488, 518, 548, 578]])

In [200]:
a1 = np.random.random((3,3))
a1

array([[0.58135137, 0.08486421, 0.91797245],
       [0.82711768, 0.4383746 , 0.48140576],
       [0.80457449, 0.40810495, 0.05579074]])

In [201]:
np.exp(a1)

array([[1.78845366, 1.08856924, 2.50420784],
       [2.28671819, 1.5501855 , 1.61834781],
       [2.23574496, 1.50396499, 1.05737639]])

In [202]:
np.log(a1)

array([[-0.54239993, -2.46670277, -0.08558789],
       [-0.18980829, -0.82468148, -0.73104479],
       [-0.21744173, -0.89623091, -2.88614742]])

In [203]:
np.round(np.random.random((2,3)) * 100)

array([[46., 52., 78.],
       [88., 93.,  7.]])

In [204]:
a1  = np.arange(1,10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [205]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
a1[1:3:]

array([2, 3])

In [207]:
a1[-1]
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [208]:
a2[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [209]:
a2[2:,0:1]

array([[8]])

In [210]:
a2[0:2,2:]

array([[2, 3],
       [6, 7]])

In [211]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [212]:
a2[::2,2::]

array([[ 2,  3],
       [10, 11]])

In [213]:
a2[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [214]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [215]:
a2[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [216]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [217]:
a3[0::,1:]

array([[[2, 3]],

       [[6, 7]]])

In [218]:
a3[1:,1,0]

array([6])

In [219]:
a3[1:,1,0]

array([6])

In [220]:
a3[0:,0,1]

array([1, 5])

In [221]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [222]:
a3[1,0,1]
import sys
sys.getsizeof(a3)

144

In [223]:
a3 = np.astype(a3, np.int16)
sys.getsizeof(a3)

160

In [224]:
a = np.arange(1,25).reshape(4,2,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [225]:
a[0::,0::]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [226]:
matrix = np.array([[1, 2], 
                   [3, 4], 
                   [5, 6]])
rows = [0,2]
columns = [0,1]
matrix[rows,columns]

array([1, 6])

In [227]:
import numpy as np

# A 3D array: (Layers, Rows, Columns)
# Shape: (3, 4, 4)
data_3d = np.arange(48).reshape(3, 4, 4)

# print("The 3D Array:")
# print(data_3d)

In [228]:
# layer = [0,1,2]
# rows = [0,1,2]
# column = [1,1,2]

# data_3d[layer,rows,column]
# data_3d

In [229]:
# layers = [0, 1, 2]
# rows   = [1, 2, 0]
# cols   = [2, 3, 0]
# data_3d[layer,rows,cols]

layers = [0,1]
rows = [1,3]
cols = [3,3]
data_3d[layers,rows,cols]

array([ 7, 31])