Creating array:

In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5,6]) # 1d array

In [3]:
b = np.arange(1,13) 
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
c = np.random.randint(1,100,24).reshape(6,4)
c

array([[87, 19, 18, 64],
       [ 1, 51, 32, 64],
       [ 9, 96, 39, 65],
       [44, 10, 96, 95],
       [37, 41, 97, 88],
       [91, 17, 80, 58]], dtype=int32)

In [5]:
d = np.linspace(1,100,6)
d

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [6]:
e = np.arange(1,25).reshape(3,4,2)
e

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [7]:
f = np.ones(12).reshape(3,4)
print(f"Array with all element 1 :\n{f}")

Array with all element 1 :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
j = np.zeros(24).reshape(4,6)
print(f"Array with all Zeros: {j}")

Array with all Zeros: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
i = np.identity(6)
i.size
i.shape
i.itemsize
i.dtype
i.nbytes

288

Attributes:

In [10]:
print("Dimension of array: ",e.ndim)
print("shape of array: ", e.shape)
print("Size of whole arry: ", e.size)
print("Total number of bits used by the array: ",e.nbytes)
print("Data types of the array: ", e.dtype)
print("item wise elements size", e.itemsize)



Dimension of array:  3
shape of array:  (3, 4, 2)
Size of whole arry:  24
Total number of bits used by the array:  192
Data types of the array:  int64
item wise elements size 8


Chinging Datatype:

In [11]:
print(i.nbytes)
i = np.astype(i,np.int8)
print(i.nbytes)

288
36


Array Operations:

In [12]:
k = np.arange(12).reshape(3,4)
l = np.arange(12,24).reshape(3,4)

In [13]:
k + l
k % l
k - l
k / l
k.nbytes == l.nbytes
k.itemsize == l.itemsize
k.dtype == l.dtype


True

In [14]:
k * 2 * l

array([[  0,  26,  56,  90],
       [128, 170, 216, 266],
       [320, 378, 440, 506]])

In [15]:
3 * l

array([[36, 39, 42, 45],
       [48, 51, 54, 57],
       [60, 63, 66, 69]])

In [16]:
3 * k

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [17]:
a2 = np.random.random((3,3))
a2 = np.round(a2 * 100)
a2

array([[95., 15., 80.],
       [67., 85., 58.],
       [10., 60., 80.]])

In [ ]:
a2_min = np.min(a2,axis=0)
a2_min
a2_max = np.max(a2)
a2_max


np.float64(95.0)