In [1]:
import numpy as np

Creating Array:

In [2]:
a_1  = np.array([1,2,3,4,5,6])
a = np.random.random(12).reshape(3,4)
b = np.random.randint(1,10,5)
c = np.random.rand(10)          # it will create array of size randomly between 0 and 1
d = np.arange(1,11).reshape(2,5)


Array (Zero, one etc):

In [3]:
e = np.ones(24).reshape(12,2)
f = np.zeros(12).reshape(3,4)
g = np.linspace(1,10)
g

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

Manipulation of Array:

In [4]:
h = np.arange(1,13).reshape(4,3)
j = h.flatten()
k = h.astype("int16")
print(h.dtype, k.dtype)
print(h.nbytes , k.nbytes)

int64 int16
96 24


Array Attributes:


In [5]:
i = np.arange(1,13).reshape(2,2,3)
print(i.ndim)
print(i.shape)
print(i.size)
print(i.nbytes)
print(i.dtype)


3
(2, 2, 3)
12
96
int64


Indexing and slicing:

In [6]:
l = np.arange(12).reshape(3,4)
l

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
l[0:,3]
l[1:,0:2]
l[1:,1:3]
l[1:,1:]


array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [8]:
m = np.arange(1,13).reshape(2,3,2)

In [9]:
m

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [10]:
m[0:,0::1,0:]


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [11]:
n = m.reshape(3,2,2)
n

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [12]:
print(m[0:1,1:2])
print(m)

[[[3 4]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
n

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [14]:
for i in n:
    print(i)
for i in a:
    print(i)
for i in a_1:
    print(i)
# a_1.ndim




[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]
[0.53238931 0.41795474 0.02893535 0.68619544]
[0.66758873 0.8980549  0.30300515 0.65990782]
[0.46491447 0.26993883 0.47048887 0.68340574]
1
2
3
4
5
6


In [15]:
n

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [16]:
a_2 = [i for i in range(10000000)]
b_1 = np.arange(1,10000000)
import sys

print(sys.getsizeof(a_2))
print(sys.getsizeof(b_1))


89095160
80000104


In [17]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
a[3:5,1:3]

array([[13, 14],
       [17, 18]])

In [19]:
a.ndim

2

In [20]:
b = np.reshape(a,(3,4,2))
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [21]:
b[0:2,0,0::]
b[0:2,2:3]

array([[[ 4,  5]],

       [[12, 13]]])

Broadcasting:

In [22]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
a + b
a * b
a - b
a / b
a[a % 2 == 0]


array([ 2,  4,  6,  8, 10, 12])

In [33]:
a = np.arange(8).reshape(2,4)
b = np.array([1,2,3,4])

# print(a.shape,b.shape)
# print(a + b)
print(a * b)

[[ 0  2  6 12]
 [ 4 10 18 28]]


In [45]:
a = np.arange(27).reshape(3,9)
b = np.arange(9)
a + b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16],
       [ 9, 11, 13, 15, 17, 19, 21, 23, 25],
       [18, 20, 22, 24, 26, 28, 30, 32, 34]])