In [1]:
import numpy as np

Sorting of Array:

In [2]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
print(a)
print(b)

[26 89 57 44 71 53 57 50 45 58 27 76 55 70 32]
[[72 59 21 39]
 [ 9 25  7 60]
 [66 32 20  9]
 [67 19 96 30]
 [94 61 83 20]
 [89 54 88 36]]


In [3]:
"Rows wise sorting of array: (by default they sorts the values row wise axis= 0)"
print(np.sort(a))
print(np.sort(b))
# columns wise sorting array:
print(np.sort(a,axis=0))
print(np.sort(b,axis=0))

"What if we have to sort in reversed order:"

print(np.sort(a)[::-1])
print(np.sort(b) [::-1])

"We can do this through the sorted"
c = sorted(a)
d = sorted(a)
print(c)

[26 27 32 44 45 50 53 55 57 57 58 70 71 76 89]
[[21 39 59 72]
 [ 7  9 25 60]
 [ 9 20 32 66]
 [19 30 67 96]
 [20 61 83 94]
 [36 54 88 89]]
[26 27 32 44 45 50 53 55 57 57 58 70 71 76 89]
[[ 9 19  7  9]
 [66 25 20 20]
 [67 32 21 30]
 [72 54 83 36]
 [89 59 88 39]
 [94 61 96 60]]
[89 76 71 70 58 57 57 55 53 50 45 44 32 27 26]
[[36 54 88 89]
 [20 61 83 94]
 [19 30 67 96]
 [ 9 20 32 66]
 [ 7  9 25 60]
 [21 39 59 72]]
[np.int32(26), np.int32(27), np.int32(32), np.int32(44), np.int32(45), np.int32(50), np.int32(53), np.int32(55), np.int32(57), np.int32(57), np.int32(58), np.int32(70), np.int32(71), np.int32(76), np.int32(89)]


Appending To Array:

In [4]:
"it will appending 200 to the last of array a"
d =np.append(a,200)
np.append(b,np.random.random((b.shape[0],1)),axis=1)


array([[72.        , 59.        , 21.        , 39.        ,  0.32584313],
       [ 9.        , 25.        ,  7.        , 60.        ,  0.64716181],
       [66.        , 32.        , 20.        ,  9.        ,  0.85612299],
       [67.        , 19.        , 96.        , 30.        ,  0.68043703],
       [94.        , 61.        , 83.        , 20.        ,  0.74501864],
       [89.        , 54.        , 88.        , 36.        ,  0.66695201]])

In [5]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [6]:
"Concatination:" 
"Row wise:"
new = np.concatenate((c,d),axis=0)
print(new)
"column wise:"
new = np.concatenate((c,d),axis=1)
print(new)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


Unique functions: (for getting unique values in array)

In [7]:
a = np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7])
unique_from_a = np.unique(a)
unique_from_a
b = np.array([[1,1,2,2],[3,3,4,4],[5,5,6,6]])
unique_from_b = np.unique(b)
unique_from_b

array([1, 2, 3, 4, 5, 6])

In [17]:
"Expaning the dimensions"
print(unique_from_a.shape)
print(np.expand_dims(unique_from_a,axis=1).shape)


(7,)
(7, 1)


np.where functions:

In [ ]:
"it return the indices of the given array when a given conditions is satisfied: "

a = np.arange(1,100)
a[np.where(a > 50)]


array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
"where() arhitecture:"
"np.where(condition,True,False): if a condition is True then replace with true wala value and if not true than replace with False:"
