In [1]:
import numpy as np

Sorting of Array:

In [2]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
print(a)
print(b)

[22 72 71  6 18 28 18  7 66 54 91 49 33 20 49]
[[44 51 85 49]
 [85 72 94 86]
 [85 36 72 63]
 [52 71 80 37]
 [41  5 78  2]
 [ 5  8 16 95]]


In [3]:
"Rows wise sorting of array: (by default they sorts the values row wise axis= 0)"
print(np.sort(a))
print(np.sort(b))
# columns wise sorting array:
print(np.sort(a,axis=0))
print(np.sort(b,axis=0))

"What if we have to sort in reversed order:"

print(np.sort(a)[::-1])
print(np.sort(b) [::-1])

"We can do this through the sorted"
c = sorted(a)
d = sorted(a)
print(c)

[ 6  7 18 18 20 22 28 33 49 49 54 66 71 72 91]
[[44 49 51 85]
 [72 85 86 94]
 [36 63 72 85]
 [37 52 71 80]
 [ 2  5 41 78]
 [ 5  8 16 95]]
[ 6  7 18 18 20 22 28 33 49 49 54 66 71 72 91]
[[ 5  5 16  2]
 [41  8 72 37]
 [44 36 78 49]
 [52 51 80 63]
 [85 71 85 86]
 [85 72 94 95]]
[91 72 71 66 54 49 49 33 28 22 20 18 18  7  6]
[[ 5  8 16 95]
 [ 2  5 41 78]
 [37 52 71 80]
 [36 63 72 85]
 [72 85 86 94]
 [44 49 51 85]]
[np.int32(6), np.int32(7), np.int32(18), np.int32(18), np.int32(20), np.int32(22), np.int32(28), np.int32(33), np.int32(49), np.int32(49), np.int32(54), np.int32(66), np.int32(71), np.int32(72), np.int32(91)]


Appending To Array:

In [4]:
"it will appending 200 to the last of array a"
d =np.append(a,200)
np.append(b,np.random.random((b.shape[0],1)),axis=1)


array([[4.40000000e+01, 5.10000000e+01, 8.50000000e+01, 4.90000000e+01,
        8.75331876e-01],
       [8.50000000e+01, 7.20000000e+01, 9.40000000e+01, 8.60000000e+01,
        1.41074002e-02],
       [8.50000000e+01, 3.60000000e+01, 7.20000000e+01, 6.30000000e+01,
        6.62882390e-01],
       [5.20000000e+01, 7.10000000e+01, 8.00000000e+01, 3.70000000e+01,
        1.78442027e-03],
       [4.10000000e+01, 5.00000000e+00, 7.80000000e+01, 2.00000000e+00,
        8.76464295e-01],
       [5.00000000e+00, 8.00000000e+00, 1.60000000e+01, 9.50000000e+01,
        9.40818304e-01]])

In [5]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [6]:
"Concatination:" 
"Row wise:"
new = np.concatenate((c,d),axis=0)
print(new)
"column wise:"
new = np.concatenate((c,d),axis=1)
print(new)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


Unique functions: (for getting unique values in array)

In [7]:
a = np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7])
unique_from_a = np.unique(a)
unique_from_a
b = np.array([[1,1,2,2],[3,3,4,4],[5,5,6,6]])
unique_from_b = np.unique(b)
unique_from_b

array([1, 2, 3, 4, 5, 6])

In [8]:
"Expaning the dimensions"
print(unique_from_a.shape)
print(np.expand_dims(unique_from_a,axis=1).shape)


(7,)
(7, 1)


np.where functions:

In [9]:
"it return the indices of the given array when a given conditions is satisfied: "

a = np.arange(1,100)
a[np.where(a > 50)]


array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
"where() arhitecture:"
"np.where(condition,True,False): if a condition is True then replace with true wala value and if not true than replace with False:"
np.where(a>50,0,a)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.unique(np.where(a % 2 == 0,0,a))


array([ 0,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
       33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

np.argmax(): 

In [17]:
"np.argmax(): it return the index of large number in a given in a specific axis"
b
np.argmax(a)

np.int64(98)