In [1]:
import numpy as np

Sorting of Array:

In [2]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
print(a)
print(b)

[63 84 33 75 51 34 18 36 58 16 67 67 51  5 62]
[[91 77 82  9]
 [82 47 55 85]
 [10 59 39  2]
 [79 85 61 45]
 [41 53 38 64]
 [61 65 41 17]]


In [3]:
"Rows wise sorting of array: (by default they sorts the values row wise axis= 0)"
print(np.sort(a))
print(np.sort(b))
# columns wise sorting array:
print(np.sort(a,axis=0))
print(np.sort(b,axis=0))

"What if we have to sort in reversed order:"

print(np.sort(a)[::-1])
print(np.sort(b) [::-1])

"We can do this through the sorted"
c = sorted(a)
d = sorted(a)
print(c)

[ 5 16 18 33 34 36 51 51 58 62 63 67 67 75 84]
[[ 9 77 82 91]
 [47 55 82 85]
 [ 2 10 39 59]
 [45 61 79 85]
 [38 41 53 64]
 [17 41 61 65]]
[ 5 16 18 33 34 36 51 51 58 62 63 67 67 75 84]
[[10 47 38  2]
 [41 53 39  9]
 [61 59 41 17]
 [79 65 55 45]
 [82 77 61 64]
 [91 85 82 85]]
[84 75 67 67 63 62 58 51 51 36 34 33 18 16  5]
[[17 41 61 65]
 [38 41 53 64]
 [45 61 79 85]
 [ 2 10 39 59]
 [47 55 82 85]
 [ 9 77 82 91]]
[np.int32(5), np.int32(16), np.int32(18), np.int32(33), np.int32(34), np.int32(36), np.int32(51), np.int32(51), np.int32(58), np.int32(62), np.int32(63), np.int32(67), np.int32(67), np.int32(75), np.int32(84)]


Appending To Array:

In [4]:
"it will appending 200 to the last of array a"
d =np.append(a,200)
np.append(b,np.random.random((b.shape[0],1)),axis=1)


array([[91.        , 77.        , 82.        ,  9.        ,  0.85295981],
       [82.        , 47.        , 55.        , 85.        ,  0.24319703],
       [10.        , 59.        , 39.        ,  2.        ,  0.42944088],
       [79.        , 85.        , 61.        , 45.        ,  0.65720601],
       [41.        , 53.        , 38.        , 64.        ,  0.52894769],
       [61.        , 65.        , 41.        , 17.        ,  0.32339251]])

In [5]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [6]:
"Concatination:" 
"Row wise:"
new = np.concatenate((c,d),axis=0)
print(new)
"column wise:"
new = np.concatenate((c,d),axis=1)
print(new)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


Unique functions: (for getting unique values in array)

In [7]:
a = np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7])
unique_from_a = np.unique(a)
unique_from_a
b = np.array([[1,1,2,2],[3,3,4,4],[5,5,6,6]])
unique_from_b = np.unique(b)
unique_from_b

array([1, 2, 3, 4, 5, 6])

In [8]:
"Expaning the dimensions"
print(unique_from_a.shape)
print(np.expand_dims(unique_from_a,axis=1).shape)


(7,)
(7, 1)


np.where functions:

In [9]:
"it return the indices of the given array when a given conditions is satisfied: "

a = np.arange(1,100)
a[np.where(a > 50)]


array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
"where() arhitecture:"
"np.where(condition,True,False): if a condition is True then replace with true wala value and if not true than replace with False:"
np.where(a>50,0,a)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
np.unique(np.where(a % 2 == 0,0,a))


array([ 0,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
       33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

np.argmax(): 

In [13]:
"np.argmax(): it return the index of large number in a given in a specific axis"
b
np.argmax(a)

np.int64(98)

In [14]:
a = np.arange(1,13).reshape(2,3,2)
np.argmax(a)


np.int64(11)

In [15]:
b = np.arange(1,25).reshape(6,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [16]:
"Column wise:"
np.argmax(b,axis=0)

array([5, 5, 5, 5])

In [17]:
"Rows wise:"
np.argmax(b, axis=1)

array([3, 3, 3, 3, 3, 3])

argmin() (Oppiste of argmax()):

In [18]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [19]:
"Columns wise:"
np.argmin(b,axis=0)


array([0, 0, 0, 0])

In [20]:
"Rows wise:"
np.argmin(b, axis=1)

array([0, 0, 0, 0, 0, 0])

np.cumulative_sum():

In [21]:
a = np.arange(1,13)
print(a)
np.cumsum(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [22]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [23]:
"Row wise:"
np.cumsum(b,axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42],
       [13, 27, 42, 58],
       [17, 35, 54, 74],
       [21, 43, 66, 90]])

In [24]:
"column wise:"
np.cumsum(b,axis=0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24],
       [28, 32, 36, 40],
       [45, 50, 55, 60],
       [66, 72, 78, 84]])

np.cumprod():

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
np.cumprod(a)

array([        1,         2,         6,        24,       120,       720,
            5040,     40320,    362880,   3628800,  39916800, 479001600])

In [ ]:
"Row wise:"
np.cumprod(b,axis=1)

array([[     1,      2,      6,     24],
       [     5,     30,    210,   1680],
       [     9,     90,    990,  11880],
       [    13,    182,   2730,  43680],
       [    17,    306,   5814, 116280],
       [    21,    462,  10626, 255024]])

In [29]:
"Columns wise:"
np.cumprod(b,axis=1)

array([[     1,      2,      6,     24],
       [     5,     30,    210,   1680],
       [     9,     90,    990,  11880],
       [    13,    182,   2730,  43680],
       [    17,    306,   5814, 116280],
       [    21,    462,  10626, 255024]])