In [61]:
import numpy as np

Sorting of Array:

In [62]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
print(a)
print(b)

[74 31 52 10 73 36 26 76  9 72 76 89 99 82 78]
[[83 34  8 25]
 [99 65 38 86]
 [51 52 41 31]
 [93 60 17  8]
 [ 1  1 97 45]
 [99 68 80 59]]


In [63]:
"Rows wise sorting of array: (by default they sorts the values row wise axis= 0)"
print(np.sort(a))
print(np.sort(b))
# columns wise sorting array:
print(np.sort(a,axis=0))
print(np.sort(b,axis=0))

"What if we have to sort in reversed order:"

print(np.sort(a)[::-1])
print(np.sort(b) [::-1])

"We can do this through the sorted"
c = sorted(a)
d = sorted(a)
print(c)

[ 9 10 26 31 36 52 72 73 74 76 76 78 82 89 99]
[[ 8 25 34 83]
 [38 65 86 99]
 [31 41 51 52]
 [ 8 17 60 93]
 [ 1  1 45 97]
 [59 68 80 99]]
[ 9 10 26 31 36 52 72 73 74 76 76 78 82 89 99]
[[ 1  1  8  8]
 [51 34 17 25]
 [83 52 38 31]
 [93 60 41 45]
 [99 65 80 59]
 [99 68 97 86]]
[99 89 82 78 76 76 74 73 72 52 36 31 26 10  9]
[[59 68 80 99]
 [ 1  1 45 97]
 [ 8 17 60 93]
 [31 41 51 52]
 [38 65 86 99]
 [ 8 25 34 83]]
[np.int32(9), np.int32(10), np.int32(26), np.int32(31), np.int32(36), np.int32(52), np.int32(72), np.int32(73), np.int32(74), np.int32(76), np.int32(76), np.int32(78), np.int32(82), np.int32(89), np.int32(99)]


Appending To Array:

In [64]:
"it will appending 200 to the last of array a"
d =np.append(a,200)
np.append(b,np.random.random((b.shape[0],1)),axis=1)


array([[83.        , 34.        ,  8.        , 25.        ,  0.13138788],
       [99.        , 65.        , 38.        , 86.        ,  0.31961727],
       [51.        , 52.        , 41.        , 31.        ,  0.14266322],
       [93.        , 60.        , 17.        ,  8.        ,  0.65260661],
       [ 1.        ,  1.        , 97.        , 45.        ,  0.65421249],
       [99.        , 68.        , 80.        , 59.        ,  0.95775446]])

In [65]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [66]:
"Concatination:" 
"Row wise:"
new = np.concatenate((c,d),axis=0)
print(new)
"column wise:"
new = np.concatenate((c,d),axis=1)
print(new)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


Unique functions: (for getting unique values in array)

In [67]:
a = np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7])
unique_from_a = np.unique(a)
unique_from_a
b = np.array([[1,1,2,2],[3,3,4,4],[5,5,6,6]])
unique_from_b = np.unique(b)
unique_from_b

array([1, 2, 3, 4, 5, 6])

In [68]:
"Expaning the dimensions"
print(unique_from_a.shape)
print(np.expand_dims(unique_from_a,axis=1).shape)


(7,)
(7, 1)


np.where functions:

In [69]:
"it return the indices of the given array when a given conditions is satisfied: "

a = np.arange(1,100)
a[np.where(a > 50)]


array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [70]:
"where() arhitecture:"
"np.where(condition,True,False): if a condition is True then replace with true wala value and if not true than replace with False:"
np.where(a>50,0,a)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [71]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [72]:
np.unique(np.where(a % 2 == 0,0,a))


array([ 0,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
       33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

np.argmax(): 

In [73]:
"np.argmax(): it return the index of large number in a given in a specific axis"
b
np.argmax(a)

np.int64(98)

In [74]:
a = np.arange(1,13).reshape(2,3,2)
np.argmax(a)


np.int64(11)

In [75]:
b = np.arange(1,25).reshape(6,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [76]:
"Column wise:"
np.argmax(b,axis=0)

array([5, 5, 5, 5])

In [77]:
"Rows wise:"
np.argmax(b, axis=1)

array([3, 3, 3, 3, 3, 3])

argmin() (Oppiste of argmax()):

In [78]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [79]:
"Columns wise:"
np.argmin(b,axis=0)


array([0, 0, 0, 0])

In [80]:
"Rows wise:"
np.argmin(b, axis=1)

array([0, 0, 0, 0, 0, 0])

np.cumulative_sum():

In [81]:
a = np.arange(1,13)
print(a)
np.cumsum(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [82]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [83]:
"Row wise:"
np.cumsum(b,axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42],
       [13, 27, 42, 58],
       [17, 35, 54, 74],
       [21, 43, 66, 90]])

In [84]:
"column wise:"
np.cumsum(b,axis=0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24],
       [28, 32, 36, 40],
       [45, 50, 55, 60],
       [66, 72, 78, 84]])

np.cumprod():

In [85]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [86]:
np.cumprod(a)

array([        1,         2,         6,        24,       120,       720,
            5040,     40320,    362880,   3628800,  39916800, 479001600])

In [87]:
"Row wise:"
np.cumprod(b,axis=1)

array([[     1,      2,      6,     24],
       [     5,     30,    210,   1680],
       [     9,     90,    990,  11880],
       [    13,    182,   2730,  43680],
       [    17,    306,   5814, 116280],
       [    21,    462,  10626, 255024]])

In [88]:
"Columns wise:"
np.cumprod(b,axis=1)

array([[     1,      2,      6,     24],
       [     5,     30,    210,   1680],
       [     9,     90,    990,  11880],
       [    13,    182,   2730,  43680],
       [    17,    306,   5814, 116280],
       [    21,    462,  10626, 255024]])

np.percentile()


In [89]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
np.percentile(a,75)

np.float64(9.25)

In [91]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [92]:
np.percentile(b,75,axis=1)

array([ 3.25,  7.25, 11.25, 15.25, 19.25, 23.25])

In [93]:
np.percentile(b,75,axis=0)

array([16., 17., 18., 19.])

In [94]:
a = np.random.randint(1,101,20).reshape(5,4)
a

array([[ 5, 39, 42, 42],
       [93, 32, 53, 26],
       [89, 51, 49, 62],
       [98, 34, 49, 16],
       [21, 20, 33, 66]], dtype=int32)

In [95]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])


(array([1, 1, 3, 4, 4, 2, 2, 0, 1, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [96]:
c,d = np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])


correlation coeffient:

In [97]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin(): 

it searchs whethar element are present or not in the array.

In [98]:
a

array([[ 5, 39, 42, 42],
       [93, 32, 53, 26],
       [89, 51, 49, 62],
       [98, 34, 49, 16],
       [21, 20, 33, 66]], dtype=int32)

In [99]:
elements = [40,30,2,36,15,73,92,84,37,91,59,69,50,89,98,0,1,3,4,40]

np.isin(a,elements)

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [100]:
a[np.isin(a,elements)]

array([89, 98], dtype=int32)

Flipping row and columns:
np.flip()

In [101]:
print(a)
"Rows wise flipping"
np.flip(a,axis=1)

[[ 5 39 42 42]
 [93 32 53 26]
 [89 51 49 62]
 [98 34 49 16]
 [21 20 33 66]]


array([[42, 42, 39,  5],
       [26, 53, 32, 93],
       [62, 49, 51, 89],
       [16, 49, 34, 98],
       [66, 33, 20, 21]], dtype=int32)

In [102]:
"Columns wise flipping:"
np.flip(a,axis=0)

array([[21, 20, 33, 66],
       [98, 34, 49, 16],
       [89, 51, 49, 62],
       [93, 32, 53, 26],
       [ 5, 39, 42, 42]], dtype=int32)

In [103]:
"Both rows and columns flipping:"
np.flip(a)

array([[66, 33, 20, 21],
       [16, 49, 34, 98],
       [62, 49, 51, 89],
       [26, 53, 32, 93],
       [42, 42, 39,  5]], dtype=int32)